### ISSUE TITLE
conversions

### ISSUE THREAD

**Issue by dskaggs** [ryanguill/watney#15]
Translate C to F and back whenever a temperature is found in a message formatted such as 25c or 75f

**Comment by mjhagen** [comment]
metric to/from imperial as well?

**Comment by ryanguill** [comment]
I think theres a lot of possibilities here, just want to make sure it doesn't get too annoying with it interjecting all the time.  I think theres lots of conversions that would be useful though.

**Comment by dskaggs** [comment]
That could be handy, but good point about being chatty. Maybe that needs to be converted to a command rather than just auto injected if we start putting a lot of conversions

`!convert 25c`
`!convert 750mm`
`!convert 12.5in`

**Comment by ryanguill** [comment]
:+1:

**Comment by ryanguill** [comment]
could also be something we could do with google translate?

**Comment by dskaggs** [comment]
Google Translate API says it's a paid service and only talks about translating languages, not these types of conversions from what I'm reading right now.

**Comment by ryanguill** [comment]
boo to paid, but I was meaning for actual language translations.  not to worry about it for now though.

**Comment by ryanguill** [comment]
@dskaggs I think we did everything from this issue, so im going to go ahead an close, but let me know if I missed something and ill reopen or we can create a new issue.
