### ISSUE TITLE
Add support for plugins sub-folders

### ISSUE THREAD

**Issue by dskaggs** [ryanguill/watney#27]
Add a recursive loading mechanism so that plugins can be organized in their own folders to facilitate writing plugins that are not distributed as part of the core Watney code base and/or are developed in their own Git repos. Bonus points if we can figure out a way to include them in a file like package.json and have them installed on `npm install`.

**Comment by atuttle** [comment]
It would be trivial to add them to package.json and have `npm install` download them... the tricky part is then using require() to load them. But I do like this idea and think we should pursue it for all plugins.

:+1:

**Comment by ryanguill** [comment]
if you do it through npm we lose the es6 stuff though.  It only works for the things loaded that arent in node_modules.

**Comment by dskaggs** [comment]
It would help in the situation I ran into last night where I'm writing a plugin for our private API that can never be published back to the main code base.

Extra special bonus points if we can auto load a plugin-specific config file as the plugin is being loaded (but maybe that's another ticket).

**Comment by dskaggs** [comment]
@ryanguill Maybe NPM isn't the way...maybe it's a Bower thing. I've used Bower to install dependencies where I gave it the full path to the Git repo. And you can set up a .bowerrc file that tells it where to put the dependencies it downloads.

**Comment by atuttle** [comment]
Hmmm... well I think we should stick with ES6 for now. 

Looking at the code in main.js, I think the first speed bump is that we don't want to load everything out of node_modules as a plugin, so we need a list (in addition to what's in package.json's dependencies); and then we may need to standardize the root .js file for the plugin instead of loading any/every js file. (watney-plugin.js?)

"watney" is available on NPM :)

**Comment by atuttle** [comment]
To clarify my last comment ~ 

@ryanguill I saw that you said babel won't work for anything in node_modules -- is that a hard and fast thing about Babel? I kind of assumed there would be a way around it if we know which modules we want to load using Babel?

**Comment by ryanguill** [comment]
I think so without going through and specifying each dependency.  The way we use it right now, all require() calls that dont go through node_modules are transpiled - transpiling an es5 npm dep might have negative side effects.  You can do it, but its not recommended anyway.

There may be some way to discover and then transpile each plugin and allowing each plugin to be a package, but that starts adding a lot of complexity.

**Comment by atuttle** [comment]
Ah well. Maybe we need a watney.json then?

**Comment by ryanguill** [comment]
There is a way to specify a regex to ignore or include based on the filename, and we can also base it on extensions, but I really don't like either option. I dont want to use a different extension and I don't really want to say you've got to name your stuff in a certain way to get transpiled. 

If we go the route of needing to explicitly specify the plugins (a la watney.json) i'd rather give you the option there to transpile or not.  The only way I can think of at the moment that we could make this work is if we change the babel stuff to transpile to es5 manually and write that out to disk and then require() from there.  Not terrible but a bit of work.  So far I think this is the best option.

**Comment by ryanguill** [comment]
This has been completed - watney running in cfml-slack has been running this code for a while now without any issues. going to close this, feel free to open a new issue with any specific discussions, problems or ideas.
