### ISSUE TITLE
!restart command should indicate when restart is complete

### ISSUE THREAD

**Issue by atuttle** [ryanguill/watney#31]
Currently he just says, "restarting..." and then kills himself. I assume you've got something like `forever` keeping him going.

What if, before he commits process suicide, he writes a file that is noticed on startup that tells him to announce his return. It could indicate the room to announce in (e.g. where he was told to restart), and it could store the current system time, which could be used on startup to calculate the amount of time taken to restart.

> **watney:** I'm back!  🕟Restart time: 8.352s

**Comment by ryanguill** [comment]
systemd, but yeah same concept.

I'd rather use redis for that, just check the existence of a key on startup, but overall :+1:

**Comment by atuttle** [comment]
Heh, I've been away from the project for too long. Kinda forgot about redis. :)

**Comment by ryanguill** [comment]
this was a bit more complicated than I thought at first blush - had to keep track of what channel the restart command was given from to know where to announce that hes back, and had to find a way to know when the connection was really back to do the announcement, but looks like everything is there and working.

**Comment by atuttle** [comment]
Noice
