### ISSUE TITLE
Intercept long messages

### ISSUE THREAD

**Issue by dajester2013** [ryanguill/watney#32]
It seems that a common recurrance is a new member posting a long block of code in a message without using a snippet, followed by an admonishment by another user.  Watney would be great for intercepting these and automatically handling the situation.

Some options that come to mind - I don't know if all of these are possible using Slack APIs:
- attempt to create a snippet automatically?
- reject the message
- automatically respond with a message concerning code pasting
  - DM or tag the offending user?

I would say this should kick in for posts that contain 6+ line breaks.  That should allow for up to a message followed by a code block with up to 3 LOC:

<pre>
msg
```
code line 1
code line 2
code line 3
```
</pre>

**Comment by ryanguill** [comment]
So I can do everything except for deleting the offending message, the bot user isnt authorized to delete someone elses message.  I haven't tried making the bot user an admin, I dont think thats a viable option really.

Do you think it would be good enough just to send a dm with a link to the gist and just ask the user to delete their message?

**Comment by seancorfield** [comment]
If Watney can automatically gist the message and send them a link and a message, that's awesome yes that's enough in my opinion.
